---
- hosts: webservers
  become: true

  roles:
    - ansistrano.deploy

  vars_files:
    - vars/provision_vault.yml
    - vars/deploy_vault.yml
    - vars/vars.yml
    - vars/provision_vars.yml
    - vars/deploy_vars.yml

  vars:
    ansistrano_deploy_via: "rsync"
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: "{{ project_deploy_path }}"
    ansistrano_keep_releases: 5
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/deploy/after-symlink.yml"
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/deploy/after-update-code.yml"
    ansistrano_shared_paths:
      - "{{ project_web_root }}/sites/default/files"
